DivMaps/Models/DivCard.cs
namespace DivMaps.Models
{
    public class DivCard
    {
        public string Name { get; set; }
        public double ChaosValue { get; set; }
        public int StackSize { get; set; }
        public double DropWeight { get; set; }
    }
}

DivMaps/Models/DivCardViewModel.cs
namespace DivMaps.Models
{
    public class DivCardViewModel
    {
        public string Name { get; set; }
        public double ChaosValue { get; set; }
        public int StackSize { get; set; }
        public double DropWeight { get; set; }
        public double Value { get; set; }
        public DivCardViewModel(string name, double chaosValue, int stackSize, double dropWeight, double value) 
        {
            Name = name;
            ChaosValue = chaosValue;
            StackSize = stackSize;
            DropWeight = dropWeight;
            Value = value;
        }
    }
}

DivMaps/Models/DivMapsRequestModel.cs
namespace DivMaps.Models
{
    public class DivMapsRequestModel
    {
        public double MinValue { get; set; }
        public bool Scarab { get; set; }
        public int FavSlots { get; set; }
    }
}

DivMaps/Models/Map.cs
namespace DivMaps.Models
{
    public class Map
    {
        public string Name { get; set; }
        public List<DivCard> DivCards { get; set; }
        public Map(string name, List<DivCard> divCards)
        {
            Name = name;
            DivCards = divCards;
        }
    }
}

DivMaps/Models/MapSetViewModel.cs
namespace DivMaps.Models
{
    public class MapSetViewModel
    {
        public List<string> Maps { get; set; }
        public double ExpectedValue { get; set; }
        public List<DivCardViewModel> Pool { get; set; }
        public MapSetViewModel()
        {

        }
        public MapSetViewModel(List<string> maps, double expectedValue, List<DivCardViewModel> pool)
        {
            Maps = maps;
            ExpectedValue = expectedValue;
            Pool = pool;
        }
    }
}

DivMaps/Models/PoeNinjaResponseModel.cs
namespace DivMaps.Models
{
    public class PoeNinjaResponseModel
    {
        public List<DivCard> Lines { get; set; }
    }
}

DivMaps/Models/ResponseViewModel.cs
namespace DivMaps.Models
{
    public class ResponseViewModel
    {
        public List<MapSetViewModel> MapSets { get; set; }
        public bool Scarab { get; set; }
        public double MinValue { get; set; }
        public ResponseViewModel(List<MapSetViewModel> mapSets, bool scarab, double minValue)
        {
            MapSets = mapSets;
            Scarab = scarab;
            MinValue = minValue;
        }
    }
}

DivMaps/Controllers/ApiController.cs
using System.Diagnostics;

using DivMaps.Models;

using Microsoft.AspNetCore.Mvc;

namespace DivMaps.Controllers
{
    [Route("/api")]
    public class ApiController : Controller
    {
        private readonly DataContainer dataContainer;

        public ApiController(DataContainer dataContainer)
        {
            this.dataContainer = dataContainer;
        }

        [HttpPost("maps")]
        public IActionResult GetMaps([FromForm]DivMapsRequestModel data)
        {
            double minValue = data?.MinValue ?? 0;
            bool scarab = data?.Scarab ?? false;
            int favSlots = Math.Clamp(data?.FavSlots ?? 12, 1, 12);

            int topSetsToStore = 100;

            bool allowRepetition = true;
            int repetitionOffset = allowRepetition ? 0 : 1;

            List<Map> maps = dataContainer.Maps;
            if (maps is null)
                return PartialView(new ResponseViewModel(new List<MapSetViewModel>(), scarab, minValue));

            List<MapSet> curSets = new List<MapSet>();
            for (int i = 0; i <= maps.Count - favSlots; i++)
                curSets.Add(new MapSet(new List<Map>() { maps[i] }, i + repetitionOffset, minValue, scarab));

            if (favSlots == 1)
                curSets = curSets.OrderByDescending(set => set.ExpectedValue).ToList();

            for (int i = 2; i <= favSlots; i++)
            {
                List<MapSet> nextSets = new List<MapSet>();
                foreach (MapSet set in curSets)
                    for (int j = set.RemainingMapsStart; j < maps.Count - favSlots + i; j++)
                        nextSets.Add(new MapSet(set.Maps.Concat(new List<Map>() { maps[j] }).ToList(), j + repetitionOffset, minValue, scarab));
                curSets = nextSets.OrderByDescending(set => set.ExpectedValue).Take(topSetsToStore).ToList();
            }
            return PartialView(new ResponseViewModel(curSets.Take(5)
                .Select(set => new MapSetViewModel(set.Maps.Select(map => map.Name).ToList(), set.ExpectedValue, set.Pool.ToList())).ToList(), scarab, minValue));
        }

        private class MapSet
        {
            public List<Map> Maps { get; }
            public int RemainingMapsStart { get; }
            private List<DivCardViewModel> pool;
            public IReadOnlyList<DivCardViewModel> Pool => pool;
            public double ExpectedValue { get; }
            public MapSet(List<Map> maps, int remainingMapsStart, double minValue, bool scarab)
            {
                Maps = maps;
                RemainingMapsStart = remainingMapsStart;

                IEnumerable<DivCard> cards = Maps.SelectMany(map => map.DivCards).Distinct();
                double totalWeight = cards.Sum(card => card.DropWeight);
                pool = cards.Select(card => new DivCardViewModel(card.Name, card.ChaosValue, card.StackSize, card.DropWeight,
                    card.ChaosValue >= minValue ? card.ChaosValue * card.DropWeight / totalWeight * (scarab ? (4.0 + card.StackSize) / 5.0 : 1.0) : 0.0))
                    .OrderByDescending(card => card.Value).ToList();
                ExpectedValue = pool.Sum(card => card.Value) * (1.0 + maps.Distinct().Count() / 10.0);
            }
        }
    }
}

DivMaps/Controllers/HomeController.cs
using System.Diagnostics;

using DivMaps.Models;

using Microsoft.AspNetCore.Mvc;

namespace DivMaps.Controllers
{
    [Route("/")]
    public class HomeController : Controller
    {
        private readonly DataContainer dataContainer;

        public HomeController(DataContainer dataContainer)
        {
            this.dataContainer = dataContainer;
        }

        [HttpGet()]
        public IActionResult Index()
        {
            return View(model: dataContainer.LastUpdate.ToString("HH:mm:ss") + " utc");
        }
    }
}

DivMaps/Views/Home/Index.cshtml
@model string

<div>
    <grid>
        <div style="width: 33%; display: inline-block; vertical-align: top; color: white;">
            <div style="float: left; margin-left: 20px; margin-top: 10px;">
                <p style="font-weight: 500; font-size: 20px; margin-bottom: 2px; text-align: center;">
                    What does this tool do?
                </p>
                <p style="text-align: center;">
                    It calculates close approximate to best sets of maps to favorite with new <br />
                    Divination Scarab of Curation based on current div card prices on <a href="https://poe.ninja/economy/affliction/divination-cards">poe.ninja</a>. <br />
                    It can account for new Divination Scarab of Completion which affects different <br />
                    stack sizes differently, for different number of favorite map slots, and for <br />
                    <a href="https://divicards-site.pages.dev/weights">droprates</a> provided by <a href="https://discord.gg/3VxKY6gt7j">poe data science group</a>.
                </p>
            </div>
        </div>
        <div style="width: 33%; display: inline-block;">
            <div class="update-time">
                Prices last updated: @Model
            </div>
            <form id="filters_form" asp-action="GetMaps" asp-controller="Api">
                <div style="text-align: center;">
                    <div style="display: inline-block">
                        <p class="form-text">Min div card price (in chaos): </p> <input name="MinValue" type="number" value="10" class="form-value" />
                    </div>
                    <div style="display: inline-block">
                        <div data-toggle="tooltip" data-placement="bottom" title="Div cards with price lower than specified will be ignored when calculating their value (their drop weight will still be included for other div cards).">
                            <p class="tooltip-text"> ? </p>
                        </div>
                    </div>
                </div>
                <div style="margin-top: 3px; text-align: center;">
                    <div style="display: inline-block">
                        <p class="form-text">With Divination Scarab of Completion: </p> <input name="Scarab" type="checkbox" class="form-checkbox" value="true" checked />
                    </div>
                    <div style="display: inline-block;">
                        <div data-toggle="tooltip" data-placement="bottom" title="Divination Scarab of Completion adds 20% chance to drop div card as full stack, which affects values differently depending on div card stack size. Effect: divCardValue * (4 + stackSize) / 5">
                            <p class="tooltip-text"> ? </p>
                        </div>
                    </div>
                </div>
                <div style="margin-top: 3px; margin-bottom: 3px; text-align: center;">
                    <div style="display: inline-block">
                        <p class="form-text">Favorite map slots: </p> <input name="FavSlots" type="number" class="form-value" value="12" min="1" max="12"/>
                    </div>
                    <div style="display: inline-block;">
                        <div data-toggle="tooltip" data-placement="bottom" title="How many maps to combine when calculating map set value.">
                            <p class="tooltip-text"> ? </p>
                        </div>
                    </div>
                </div>
                <div style="text-align: center">
                    <input type="submit" value="Calculate" class="submit-button" data-original-title="Tooltip." data-placement="right" data-toggle="tooltip" />
                </div>
            </form>
        </div>
        <div style="width: 33%; display: inline-block; vertical-align: top;">
            <div class="credits">
                <p>Created by: Notrum666(<a href="https://github.com/Notrum666">github</a>)(<a href="https://www.pathofexile.com/account/view-profile/Notrum666">PoE</a>), <a data-toggle="tooltip" data-placement="bottom" title="abstained from leaving any links">Hrenaki</a></p>
                <p>Hosted by: SilenceIX(<a href="https://www.pathofexile.com/account/view-profile/Ilece">PoE</a>)</p>
            </div>
        </div>
    </grid>
    <div id="table-container" class="table-container">

    </div>
</div>

<script>
    $(function () {
        $("[data-toggle='tooltip']").tooltip();
    });

    function GetMaps()
    {
        form = $('#filters_form');

        url = form.attr('action');
        data = form.serialize();

        $.ajax({
            type: 'POST',
            url: url,
            data: data,
            success: function (view) {
                $('#table-container').html(view);
            }
        });

        return false;
    }

    $('#filters_form').submit(GetMaps);
</script>

DivMaps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DivMaps</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DivMaps.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/css/bootstrap-select.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/js/bootstrap-select.min.js"></script>
</head>
<body>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (m, e, t, r, i, k, a) {
            m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) };
            m[i].l = 1 * new Date();
            for (var j = 0; j < document.scripts.length; j++) { if (document.scripts[j].src === r) { return; } }
            k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(96848530, "init", {
            clickmap: true,
            trackLinks: true,
            accurateTrackBounce: true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/96848530" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>